### ISSUE TITLE
Upgradable package icon remains after upgrade

### ISSUE THREAD

**Issue by dschaper** [XavierBerger/RPi-Monitor#118]
After getting a package update notification, updating packages and running both the `updatePackagesStatus.pl` and manually running `systemctl start rpimonitord-upgradable` the package count resets to 0 but the icon remains and hovering over the icon lists the old package(s) to be upgraded. 

![capture](https://cloud.githubusercontent.com/assets/2782850/9429352/a0de2040-4981-11e5-8d30-b6e6890be0ae.PNG)

**Comment by XavierBerger** [comment]
I don't use **Arch Linux**. I only integrate the pull request proposed for this distro.
It looks that the script `updatePackagesStatus.pl` updating the file `/var/lib/rpimonitor/updatestatus.txt` have a bug. Pull request fixing this issue is welcome (in `devel` branch of course)

**Comment by XavierBerger** [comment]
Unless I initially thought, this issue wasn't located into `updatePackagesStatus.pl` but in javascript.
I managed to reproduce it and fix it.

**Comment by XavierBerger** [comment]
It looks that this bug is still present (but now in perl part...)

Version 2.11.
- Install a brand new `Raspbian Jessie Lite`
- Install **RPi-Monitor**
- Browse `rpi:8888` and activate auto-refresh option
- Execute `sudo /etc/init.d/rpimonitor` update
- execute `sudo apt-get upgrade`
- In Web interface, the number of package to upgrade is 0 but list of package is still displayed
- `rpi:8888/dynamic.json` show that the information has been sent by the perl script

**Comment by TimJDFletcher** [comment]
The problem is that the apt-get hook is called on dpkg (install / remove etc) actions not apt-get update. The correct hook is this: 

# Update rpimonitor status
```
APT::Update::Post-Invoke {
  "echo 'Update rpimonitor Packages Status' && /usr/share/rpimonitor/scripts/updatePackagesStatus.pl";
};
```

**Comment by TimJDFletcher** [comment]
Just submitted a pull request to resolve this
