### ISSUE TITLE
 Can not get information (dynamic.json) from RPi-Monitor server.

### ISSUE THREAD

**Issue by XavierBerger** [XavierBerger/RPi-Monitor#12]
Similar problem again. :( I can't repair it with updates and upgrades.

All Statistics are working, but Status page halted with the "dynamic.json" error message.

This isn't browser problem, because I tested it with a lot of versions and different devices.

I tried following commands:

sudo apt-get update && sudo service rpimonitor update
sudo apt-get update
sudo apt-get upgrade
sudo reboot

These steps help previously under the same condition. Not now. :(

All other services are working probably.

How can I debug it?

**Comment by patricktokeeffe** [comment]
fwiw, I experienced this because of a missing data source directory. I have data sources inside `/run/ebam/` but that directory was not being created at boot. All 3 server processes were starting and the website would load, but it produced *dynamic.json* errors. Creating the missing dir and restarting fixed my instance immediately.
