### ISSUE TITLE
Options Dropdown Doesn't Reflect Altered Delay

### ISSUE THREAD

**Issue by EdanStarfire** [XavierBerger/RPi-Monitor#136]
I'm using wireless XBee sensors and only actually polling via the sensors on demand from the Pi, so 10s was WAY too fast.  I updated my delay to 1 minute (daemon.delay=60) in order to slow down polling. However, even though the RRDs regenerated with the correct ranges (60s, 6m, 60m, 3h, 6h) the options page still shows the default ranges (10s, 60s, 10m, 30m, 60m).  When selected, the appropriate relative selection sets as the default (options=60s --> RRD=6m, options=3h --> RRD=30m) so it only looks like a display bug.  Might have something to do with the custom RRD feature that was added.
![image](https://cloud.githubusercontent.com/assets/16409404/11971054/bf1a9588-a904-11e5-908e-c77f86b396af.png)
![image](https://cloud.githubusercontent.com/assets/16409404/11971057/c9353956-a904-11e5-9c3c-5b6494057953.png)

**Comment by XavierBerger** [comment]
Fixed in 2.11. Default graph propose the choose `Graph n°X` This will avoid synchronization problem if you decide to change the pooling period.

**Note**: The new repository is hosted by http://giteduberger.fr. 
To test `v2.11-betaX` You can update you `apt` configuration with this file: [/etc/apt/sources.list.d/rpimonitor.list](https://raw.githubusercontent.com/XavierBerger/RPi-Monitor/devel/src/etc/apt/sources.list.d/rpimonitor.list) and perform installation with `apt-get`.
