### ISSUE TITLE
Wrong x-scale on disc-related statistics

### ISSUE THREAD

**Issue by deMattin** [XavierBerger/RPi-Monitor#23]
As first mentioned here: https://github.com/XavierBerger/RPi-Monitor/issues/22#issuecomment-26673172 I have an issue with wrong x-scale on some statistics.
This is with all values, that have this static-data in (discs, sd, swap) and memory. The other scales are ok.

The graph is drawn correctly but the x-scale (date/time) has always fixed values.
On day-view it goes from 01:13:30 to 01:13:20 (full day).

It first occurs with version 2.4 but is the same after updating to 2.5 (complete reinstall).
Tried it also with the default configs and with deleting the rrd-files - same problem.

Does anybody have an idea?
Does noone else have this problem?
Especially feedback form users with a very first and clean install of rpimonitor would be very helpfull to me.

**Comment by licaon-kter** [comment]
Got bit by this because running with systemd two processes are started as **root:root**, but a third one as **pi:pi**. Hence `empty.rrd` ends up owned by **pi:pi**, but installing from Git the **/var/lib/rpimonitor** path is owned by **root:root** and user pi can't actually update the file, hence the skewed time for some stats.

The fix (in my case at least): `chown -R pi:pi /var/lib/rpimonitor`
And add this to systemd:
```
...
[Unit]
...
User=pi
Group=pi
...
```

/PS: if running as user pi the CPU freq is `null`, edit the line in `templates/cpu.conf` like this: `dynamic.1.source=sudo cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq`
