### ISSUE TITLE
[enhancement] Add a shutdown button

### ISSUE THREAD

**Issue by lauhub** [XavierBerger/RPi-Monitor#24]
Hi,
Would it be possible to add a button that allows to shutdown the RPI?

It would call a shell command like "sudo shutdown -h now".

Thank you for your nice product !

**Comment by WolfganP** [comment]
+1 on this feature. I use my RasPi as a headless system and having a remote shutdown command would really fit well in the system w/o need to install anything else or type into shellinabox.

As 3 years and many versions passed by since this issue was opened originally, is there any change of heart on getting this implemented, if not at least provide tips on how to implement the feature as an add-on?
Thx, Wolf.
