### ISSUE TITLE
Top3 with reverse-proxy don't work in Status page

### ISSUE THREAD

**Issue by shudack** [XavierBerger/RPi-Monitor#241]
Hi,

Top3 with reverse-proxy don't work in Status page, in localhost:8888 it's work.

Can you help me?

![capturar2](https://user-images.githubusercontent.com/17851196/46181504-2b402900-c2be-11e8-9195-c38e3815b17c.PNG)
![capturar](https://user-images.githubusercontent.com/17851196/46181505-2bd8bf80-c2be-11e8-83d6-85408977217c.PNG)

Thanks.

Best regards,
Shudack

**Comment by Leepic** [comment]
Do you have any error (eg. HTTP code 404) on your browser console (F12) when you load the web page behind your reverse proxy?

Do you have access to this page `https:/your-domain.tld/addons/top3/top3.html` behind your reverse proxy?

Regards,
Leepic

**Comment by shudack** [comment]
I see this on the console:

![2019-01-04 09_27_45-rpi-monitor flaviopinho](https://user-images.githubusercontent.com/17851196/50681382-34e6d480-1003-11e9-93e7-5c188c7c47af.png)

Yes, I have access:

![image](https://user-images.githubusercontent.com/17851196/50681413-58118400-1003-11e9-9dfd-c60847cd9804.png)


Regards,
Shudack

**Comment by Leepic** [comment]
Your console say that `jquery.min.js `can't load. Do you have access with your browser to https://your-domain.tld/rpimonitor/js/jquery.min.js?

The file is at `/usr/share/rpimonitor/web/js/jquery.min.js`.

**Comment by shudack** [comment]
Yes, I have access to https://your-domain.tld/rpimonitor/js/jquery.min.js

![image](https://user-images.githubusercontent.com/17851196/50761205-b045c180-1261-11e9-9e66-d055e49448c7.png)

**Comment by Leepic** [comment]
Hi @shudack 

I have reproduce the problem and find the root cause. I've used the [RPi-Monitor official NginX configuration ](https://xavierberger.github.io/RPi-Monitor-docs/34_autentication.html#authentication-and-secure-access).

In F12 on my web browser I have find that _top3.html_ was not found because the request was made on _https://your-domain.tld/addons/top3/top3.html_ and not _https://your-domain.tld/rpimonitor/addons/top3/top3.html_. So I have just modify cpu.conf:

```diff
-web.status.1.content.1.line.4=InsertHTML("/addons/top3/top3.html")
+web.status.1.content.1.line.4=InsertHTML("./addons/top3/top3.html")
```
The root cause was the dot because without it the request was made on the root domain and not under the directory you are in (/rpimonitor in your case).

Can you tell me it works for you too?

**Comment by shudack** [comment]
Hi,

Thanks for help. Works now!


Best regards,
Shudack
