### ISSUE TITLE
disabled swap is 100% used

### ISSUE THREAD

**Issue by ghost** [XavierBerger/RPi-Monitor#242]
Hello,
I have disabled swap on one of my pi's. the rpimonitor shows 100% used.
`cat /proc/meminfo | grep -i swap`
`SwapCached:            0 kB`
`SwapTotal:             0 kB`
`SwapFree:              0 kB`
![swap](https://user-images.githubusercontent.com/2621746/47520809-84858300-d891-11e8-8be8-9a51518250c9.png)

**Comment by Leepic** [comment]
I have the same issue on my RaspberryPi 3B with RPi-Monitor 2.12-r0 on Raspbian 8 (Jessie).

* When I restart `sudo systemctl restart rpimonitor` with swap disabled:

![image-swap-disabled-value-zeros](https://user-images.githubusercontent.com/10730819/50665733-23c1a780-0fb2-11e9-92f0-d9c597641803.png)


* When I enable again the swap with `sudo dphys-swapfile swapon` I can see this:
![image-swap-enabled-negative-values](https://user-images.githubusercontent.com/10730819/50665395-d133bb80-0fb0-11e9-895f-4d247ad2a436.png)

* When I restart `sudo systemctl restart rpimonitor`, all is OK:

![image-swap-enabled-rpimonitord-restarted-values-ok](https://user-images.githubusercontent.com/10730819/50665632-b746a880-0fb1-11e9-92a2-05399d34af48.png)


As seen above the 100% utilization disappear when I restart rpimonitord. The root cause is because the _swap_total_ value is static and not dynamics in _swap.conf_.

@basti12203 can you replace this lines and tell me if it's OK for you too?

```
dynamic.6.name=swap_total
dynamic.6.source=/proc/meminfo
dynamic.6.regexp=SwapTotal:\s+(\d+)
dynamic.6.postprocess=$1/1024
dynamic.6.rrd=GAUGE
```

I think the value is static for betters performances as RPi-Monitor doesn't need to actualize the _swap_total_ value but only on rpimonitord restart. The _total_swap_ value rarely/never changes on a system. I think it's not a real issue because you just need to restart rpimonitord for the new values take affect.

@XavierBerger What do you think?

**Comment by ghost** [comment]
yes that works. thanks a lot. i have also change /usr/share/rpimonitor/web/js/rpimonitor.utils.js
` function Percent(value,total){
  if (total > 0) {
       return (100*value/total).toFixed(2)+"%";
  } else { return (0)+"%"; }
 }`
to fix NaN% Output

**Comment by TupaNegreiros** [comment]
I'm using `dphys-swapfile`, changing static to dynamic worked here.
It's needed to also change `dynamic.8.postprocess=$this->{'static'}->{'swap_total'} - ($1/1024)` to `dynamic.8.postprocess=$this->{'dynamic'}->{'swap_total'} - ($1/1024)`
