### ISSUE TITLE
Monitoring External HDD's

### ISSUE THREAD

**Issue by dazbobaby** [XavierBerger/RPi-Monitor#288]
I've struggled to get this working, then I looked at the code sdcard.conf and copied the requirements to storage.conf

In sdcard.conf you put:
```
static.7.name=sdcard_root_total
static.7.source=df /
static.7.regexp=\S+\s+(\d+).*\/$
static.7.postprocess=$1/1024
```
But in storage you've put:
```
static.10.name=storage1_total
static.10.source=df -t sda1
static.10.regexp=/sda1\s+(\d+)
static.10.postprocess=$1/1024
```
This failed for me everytime, I've changed it too:
```
static.10.name=storage1_total
static.10.source=df /dev/sda1
static.10.regexp=/sda1\s+(\d+)
static.10.postprocess=$1/1024
```

So I removed the -t and put /dev/sda1 and this worked for me.

Now if I could do this with a network share.
I've tried /mnt/samba and no luck
I've tried //192.168.1.1/H and no luck
I've tried /192.168.1.1/H - no luck.

Though df -h /mnt/samba works on the command line, as does df -h //192.168.1.1/H, it doesn't work for rpimonitor

Excellent work though, I love it, my thanks to you for making it.

**Comment by Conver** [comment]
I need this too, I need to be able to monitor the NAS connected to the pi running RPi-monitor

**Comment by dazbobaby** [comment]
I have my NAS connected though NFS and NFS can work too. Just df /mnt/YOUR DRIVE MOUNT FOLDER

static.11.name=storage2_total
static.11.source=df /mnt/Movies
static.11.regexp=/Movies\s+(\d+)
static.11.postprocess=$1/1024

dynamic.15.name=storage2_used
dynamic.15.source=df /mnt/Movies
dynamic.15.regexp=/Movies\s+\d+\s+(\d+)
dynamic.15.postprocess=$1/1024
dynamic.15.rrd=GAUGE

web.status.1.content.9.name=Storage
web.status.1.content.9.icon=usb_hdd.png
web.status.1.content.9.line.1="<b>/500GB HDD</b> Used: <b>"+KMG(data.storage1_used,'M')+"</b> (<b>"+Percent(data.storage1_used,data.storage1_total,'M')+"</b>) Free: <b>"+KMG(data.storage1_total-data.storage1_used,'M')+ "</b> Total: <b>"+ KMG(data.storage1_total,'M') +"</b>"
web.status.1.content.9.line.2=ProgressBar(data.storage1_used,data.storage1_total)

web.status.1.content.9.line.3="<b>Movies</b> Used: <b>"+KMG(data.storage2_used,'M')+"</b> (<b>"+Percent(data.storage2_used,data.storage2_total,'M')+"</b>) Free: <b>"+KMG(data.storage2_total-data.storage2_used,'M')+ "</b> Total: <b>"+ KMG(data.storage2_total,'M') +"</b>"
web.status.1.content.9.line.4=ProgressBar(data.storage2_used,data.storage2_total)

**Comment by GhislainOlitec** [comment]
It does not work for me

`df th /mnt/nas1Sys. de fichiers blocs de 1K   Utilisé Disponible Uti% Monté sur
/dev/sdb1          479667880 131200092  324032232  29% /mnt/nas1
`

**Comment by GhislainOlitec** [comment]
It don't work for me, I have a "NaNkB" that appears....

If i type
`df /mnt/nas1`

he returns 
`Sys. de fichiers blocs de 1K   Utilisé Disponible Uti% Monté sur`
`/dev/sdb1          479667880 131200092  324032232  29% /mnt/nas1`

so if I understand well as the "/nas1" is in the end he is not looking forward ?? I also tried with "/dev" but don't work either....

I do not know REGEX so it's difficult for me. I will deepen the thing and come back if I have a solution ... because the problem is that each reboot sdX changes and the statistics too ...

`static.20.name=nas1_total`
`static.20.source=df /mnt/nas1`
`static.20.regexp=/nas1\s+(\d+)`
`static.20.postprocess=$1/1024`

`dynamic.21.name=nas1_used`
`dynamic.21.source=df /mnt/nas1`
`dynamic.21.regexp=/nas1\s+\d+\s+(\d+)`
`dynamic.21.postprocess=$1/1024`
`dynamic.21.rrd=GAUGE`

`web.status.1.content.9.line.3="<b>/Nas1</b> Used: <b>"+KMG(data.nas1_used,'M')+"</b> (<b>"+Percent(data.nas1_used,data.nas1_total,'M')+"</b>) Free: <b>"+KMG(data.nas1_total-data.nas1_used,'M')+ "</b> Total: <b>"+ KMG(data.nas1_total,'M') +"</b>"`
`web.status.1.content.9.line.4=ProgressBar(data.nas1_used,data.nas1_total)`

EDIT:

I found! I reread the file for the sdcard and the line "static.7.regexp=\S+\s+(\d+).*\/$" gave me the solution!

Compared to the origin there is only the REGEX command to change :)

`static.20.name=nas1_total`
`static.20.source=df -t ext4`
`static.20.regexp=\S+\s+(\d+).*\/nas1$`
`static.20.postprocess=$1/1024`

`dynamic.21.name=nas1_used`
`dynamic.21.source=df -t ext4`
`dynamic.21.regexp=\S+\s+\d+\s+(\d+).*\/nas1$`
`dynamic.21.postprocess=$1/1024`
`dynamic.21.rrd=GAUGE`

It should be on a next update to change it like that directly

Congratulations for this great work ;) can be a day a translation FR lol
