### ISSUE TITLE
Addons url start with root web server.

### ISSUE THREAD

**Issue by chantonoi** [XavierBerger/RPi-Monitor#322]
When I set reverse proxy form http://127.0.0.1:8888 to https://myhost.com/rpimonitor.
Most data  has work properly, but addons eg. top3 do not work. 

A top3 addons request at https://myhost.com/addons/top3.html instead of https://myhost.com/rpimonitor/addons/top3.html

nginx config:
server {
    server_name serverstatus.xxxxx.net;

    location / {
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://192.168.1.8:1085;
    }

    location /dns1/ {
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://192.168.1.3:8888;
        proxy_redirect http://192.168.1.3:8888 https://$host/dns1;
        proxy_set_header Host $host/dns1/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    .
    .
    .
    .
}

**Comment by chantonoi** [comment]
Okay, it's done, I'm sorry to open this case. It can be easily fixed by edit the cpu.conf. Add '.' Before '/ addons'.

**Comment by Leepic** [comment]
It seem to be the same issue fixed in #241 (in develop branch).
Can you test the patch explain in [this comment](https://github.com/XavierBerger/RPi-Monitor/issues/241#issuecomment-452902311)?

PS: I sugger you to put an authentication on your public, [as describe in the doc](https://xavierberger.github.io/RPi-Monitor-docs/34_autentication.html#reverse-proxy-configuration), because currently your page is public ;).
